"""The skills installer: prefix substitution, idempotency, version staleness."""
import os
import shutil
import tempfile
import unittest

from interfacile import __version__, scaffold


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


class TestScaffold(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="ifc-test-")
        self.addCleanup(shutil.rmtree, self.root, True)

    def skill(self, name):
        return os.path.join(self.root, scaffold.SKILLS_REL, name, "SKILL.md")

    def test_install_substitutes_prefix_and_stamps_version(self):
        done = scaffold.install(self.root, "ZZ")
        self.assertTrue(all(a == "wrote" for a, _ in done))

        work = read(self.skill("work-ticket"))
        self.assertIn("ZZ-0012", work)
        self.assertNotIn("{{PREFIX}}", work)
        self.assertIn("generated by interfacile v%s" % __version__, work)

        doc = read(os.path.join(self.root, scaffold.PROCESS_DOC_REL))
        self.assertIn("ZZ-0001", doc)
        self.assertNotIn("{{PREFIX}}", doc)

    def test_reinstall_is_idempotent_and_repairs_drift(self):
        scaffold.install(self.root, "ZZ")
        self.assertTrue(all(a == "kept" for a, _ in
                            scaffold.install(self.root, "ZZ")))

        with open(self.skill("new-ticket"), "a", encoding="utf-8") as fh:
            fh.write("\nlocal drift\n")
        actions = dict((p, a) for a, p in scaffold.install(self.root, "ZZ"))
        self.assertEqual(
            actions[os.path.join(scaffold.SKILLS_REL, "new-ticket", "SKILL.md")],
            "updated")

    def test_process_doc_is_kept_unless_forced(self):
        scaffold.install(self.root, "ZZ")
        doc = os.path.join(self.root, scaffold.PROCESS_DOC_REL)
        with open(doc, "w", encoding="utf-8") as fh:
            fh.write("ours now\n")
        scaffold.install(self.root, "ZZ")
        self.assertEqual(read(doc), "ours now\n")
        scaffold.install(self.root, "ZZ", force=True)
        self.assertIn("ZZ-0001", read(doc))

    def test_stale_notice(self):
        self.assertIsNone(scaffold.stale_notice(self.root))  # nothing installed

        scaffold.install(self.root, "ZZ")
        self.assertIsNone(scaffold.stale_notice(self.root))  # current

        path = self.skill("ticket-status")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("---\nname: ticket-status\n---\n"
                     "<!-- generated by interfacile v0.0.1 -->\n")
        notice = scaffold.stale_notice(self.root)
        self.assertIn("v0.0.1", notice)
        self.assertIn("interfacile skills", notice)


if __name__ == "__main__":
    unittest.main()
