"""Install the generic ticket-flow skills and process doc into a repo.

    interfacile skills [PATH] [--force]

Copies the packaged templates into the target repo:

    .claude/skills/<name>/SKILL.md   agent skills: new-ticket, work-ticket,
                                     close-ticket, ticket-status
    tickets/README.md                the process doc — how tickets work here

Skills are managed files and are refreshed in place on every run, so `skills`
doubles as the upgrade path. The process doc is only written when missing
(or with --force), because a repo is allowed to make it its own.

Templates use {{PREFIX}} where an example ticket id needs the repo's prefix,
so nothing project-specific ever ships in the package.

Every generated file carries a version marker; `interfacile lint` compares it
against the running package and nudges when the installed flow is stale.
"""
import glob
import os
import re

from . import __version__

TEMPLATES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")
SKILLS_REL = os.path.join(".claude", "skills")
PROCESS_DOC_REL = os.path.join("tickets", "README.md")

_MARKER = ("\n<!-- generated by interfacile v%s — refresh with "
           "`interfacile skills` -->\n")
_MARKER_RE = re.compile(r"generated by interfacile v([\w.\-]+)")


def _render(path, prefix):
    with open(path, encoding="utf-8") as fh:
        return fh.read().replace("{{PREFIX}}", prefix) + _MARKER % __version__


def stale_notice(root):
    """One-line nudge when installed skills predate the running package, or
    None. Silent when a repo has no installed skills — that's a choice."""
    paths = glob.glob(os.path.join(root, SKILLS_REL, "*", "SKILL.md"))
    if not paths:
        return None
    versions = set()
    for p in paths:
        with open(p, encoding="utf-8") as fh:
            m = _MARKER_RE.search(fh.read())
        versions.add(m.group(1) if m else "unversioned")
    stale = sorted(v for v in versions if v != __version__)
    if not stale:
        return None
    shown = "/".join(("v" + v) if v[:1].isdigit() else v for v in stale)
    return ("note: installed skills are from interfacile %s; the package is "
            "v%s — run `interfacile skills` to refresh them."
            % (shown, __version__))


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def skill_names():
    base = os.path.join(TEMPLATES_DIR, "skills")
    return sorted(d for d in os.listdir(base)
                  if os.path.isfile(os.path.join(base, d, "SKILL.md")))


def install(root, prefix, force=False):
    """Install/refresh the flow into <root>. Returns [(action, relpath), ...]
    where action is 'wrote', 'updated', or 'kept'."""
    done = []
    for name in skill_names():
        src = os.path.join(TEMPLATES_DIR, "skills", name, "SKILL.md")
        rel = os.path.join(SKILLS_REL, name, "SKILL.md")
        dest = os.path.join(root, rel)
        text = _render(src, prefix)
        if os.path.exists(dest):
            with open(dest, encoding="utf-8") as fh:
                if fh.read() == text:
                    done.append(("kept", rel))
                    continue
            _write(dest, text)
            done.append(("updated", rel))
        else:
            _write(dest, text)
            done.append(("wrote", rel))

    doc = os.path.join(root, PROCESS_DOC_REL)
    if force or not os.path.exists(doc):
        _write(doc, _render(os.path.join(TEMPLATES_DIR, PROCESS_DOC_REL), prefix))
        done.append(("wrote", PROCESS_DOC_REL))
    else:
        done.append(("kept", PROCESS_DOC_REL))
    return done
